const FILE_TYPE = {
	'3g2': 'vid',
	'3gp': 'vid',
	'aac': 'aud',
	'adp': 'aud',
	'aif': 'aud',
	'asf': 'vid',
	'au' : 'aud',
	'avi': 'vid',
	'bas': 'scr',
	'bat': 'scr',
	'bmp': 'img',
	'c'  : 'scr',
	'cmd': 'scr',
	'css': 'css',
	'csv': 'txt',
	'djvu': 'img',
	'dts': 'aud',
	'dtshd': 'aud',
	'dwg': 'img',
	'dxf': 'img',
	'etx': 'txt',
	'f'  : 'scr',
	'f4v': 'vid',
	'fli': 'vid',
	'flv': 'vid',
	'fly': 'txt',
	'fpx': 'img',
	'gif': 'img',
	'h'  : 'scr',
	'h261': 'vid',
	'h263': 'vid',
	'h264': 'vid',
	'htm': 'htm',
	'html': 'htm',
	'ico': 'img',
	'ics': 'txt',
	'ini': 'txt',
	'ino': 'scr',
	'jad': 'txt',
	'java': 'jav',
	'jpeg': 'img',
	'jpg': 'img',
	'jpgv': 'vid',
	'jpm': 'vid',
	'js' : 'jav',
	'json': 'jav',
	'log': 'txt',
	'm3u': 'aud',
	'm4v': 'vid',
	'md' : 'txt',
	'mdi': 'img',
	'mid': 'aud',
	'mj2': 'vid',
	'mk3d': 'aud',
	'mka': 'aud',
	'mkv': 'vid',
	'mov': 'vid',
	'movie': 'vid',
	'mp3': 'aud',
	'mp4': 'vid',
	'mp4a': 'aud',
	'mpeg': 'vid',
	'mpg': 'vid',
	'mpga': 'aud',
	'npx': 'img',
	'oga': 'aud',
	'ogv': 'vid',
	'p'  : 'scr',
	'par': 'scr',
	'pbm': 'img',
	'pcx': 'img',
	'pdf': 'pdf',
	'pgm': 'img',
	'pic': 'img',
	'png': 'img',
	'pnm': 'img',
	'ppm': 'img',
	'psd': 'img',
	'py' : 'scr',
	'qt' : 'vid',
	'ra' : 'aud',
	'ram': 'aud',
	'ras': 'img',
	'reg': 'txt',
	'rgb': 'img',
	'rpm': 'aud',
	'rtx': 'txt',
	'rv' : 'vid',
	's'  : 'scr',
	'sh' : 'scr',
	'srt': 'txt',
	'sub': 'txt',
	'tif': 'img',
	'tiff': 'img',
	'txt': 'txt',
	'uri': 'txt',
	'vbs': 'scr',
	'vcf': 'txt',
	'vcs': 'txt',
	'wav': 'aud',
	'wax': 'aud',
	'wbmp': 'img',
	'weba': 'aud',
	'webm': 'vid',
	'webp': 'img',
	'wm' : 'vid',
	'wma': 'aud',
	'wml': 'scr',
	'wmls': 'scr',
	'wmv': 'vid',
	'wmx': 'vid',
	'wvx': 'vid',
	'xif': 'img',
	'xml': 'xml',
	'xwd': 'img',
	'yaml': 'txt',
}
